name: ♻ tofu

on:
  workflow_call:
    inputs:
      environment:
        description: The environment that the job references.
        type: string
        required: true

      working_directory:
        description: The working directory to run the OpenTofu commands in.
        type: string
        required: false
        default: "."

      tofu_version:
        description: The version of OpenTofu to install.
        type: string
        required: false
        default: latest

      backend_config:
        description: The path, relative to the working directory, of a configuration file containing the remaining arguments for a partial backend configuration.
        type: string
        required: false
        default: ""

      artifact_name:
        description: The name of the artifact to upload. If not specified, an artifact name will be generated based on the environment name.
        type: string
        required: false
        default: ""

      runs_on:
        description: The label of the runner (GitHub- or self-hosted) to run this workflow on.
        type: string
        required: false
        default: ubuntu-latest

    secrets:
      AZURE_CLIENT_ID:
        description: The client ID of the Azure AD service principal to use for authenticating to Azure.
        required: true

      AZURE_SUBSCRIPTION_ID:
        description: The ID of the Azure subscription to create the resources in.
        required: true

      AZURE_TENANT_ID:
        description: The ID of the Azure tenant to create the resources in.
        required: true

      ENCRYPTION_PASSWORD:
        description: A password used to encrypt the archive containing the OpenTofu configuration and plan file.
        required: true

# Queue jobs that target the same OpenTofu configuration.
concurrency:
  group: opentofu @ ${{ inputs.working_directory }}
  cancel-in-progress: false

permissions: {}

env:
  # Configure OpenTofu to run in automation.
  # Makes output more consistent and less confusing in workflows where users don't directly execute OpenTofu commands.
  TF_IN_AUTOMATION: true

  TF_CLI_ARGS_init: -backend-config=${{ inputs.backend_config }}

  # Configure OIDC authentication to Azure using environment variables.
  # Required by the AzureRM backend and provider.
  ARM_USE_OIDC: true
  ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  ARTIFACT_NAME: ${{ inputs.artifact_name || format('tfplan-{0}', inputs.environment) }}
  ENCRYPTION_PASSWORD: ${{ secrets.ENCRYPTION_PASSWORD }}

jobs:
  tofu-plan:
    name: OpenTofu Plan
    runs-on: ${{ inputs.runs_on }}
    if: github.actor != 'dependabot[bot]'
    environment: ${{ inputs.environment }}
    permissions:
      contents: read  # Required to checkout the repository
      id-token: write # Required to login to Azure using OIDC

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    outputs:
      upload-outcome: ${{ steps.upload.outcome }}
      artifact-id: ${{ steps.upload.outputs.artifact-id }}

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@12f4debbf681675350b6cd1f0ff8ecfbda62027b
        with:
          tofu_version: ${{ inputs.tofu_version }}
          tofu_wrapper: false
          # Wraps OpenTofu commands, exposing their stdout, stderr and exitcode.
          # It also wraps OpenTofu command outputs with debug logs, including the output of the "tofu show" command.
          # The "show" command is used to create a GitHub job summary containing the generated plan in a human-readable format.
          # If the wrapper is enabled, the debug logs will be visible in the job summary.
          # The wrapper must be disabled to prevent this.

      - name: OpenTofu Format
        id: fmt
        run: tofu fmt -check

      - name: OpenTofu Init
        id: init
        run: tofu init

      - name: OpenTofu Validate
        id: validate
        run: tofu validate

      # Create OpenTofu plan file.
      # This file contains the full configuration, including sensitive data.
      # As a result, it should be treated as a potentially-sensitive artifact.
      # Ref: https://developer.hashicorp.com/tofu/tutorials/automation/automate-tofu#plan-and-apply-on-different-machines
      - name: OpenTofu Plan
        id: plan
        # Start Bash without fail-fast behavior.
        # Required in order to check exitcode.
        # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#exit-codes-and-error-action-preference
        shell: bash {0}
        run: |
          tofu plan -input=false -out=tfplan -detailed-exitcode
          exitcode=$?
          if [[ "$exitcode" == 1 ]]; then
            exit "$exitcode"
          fi
          echo "exitcode=$exitcode" >> "$GITHUB_OUTPUT"

      # Some plans are too large to be stored in environment variables or step outputs, resulting in an error.
      # To bypass this, the plan must be explicitly read during this step using the "tofu show" command.
      - name: Create job summary
        # Only run if OpenTofu Plan succeeded with non-empty diff (changes present).
        # Ref: https://developer.hashicorp.com/tofu/cli/commands/plan#detailed-exitcode
        if: steps.plan.outputs.exitcode == 2
        shell: bash {0}
        env:
          TF_FMT_OUTCOME: ${{ steps.fmt.outcome }}
          TF_INIT_OUTCOME: ${{ steps.init.outcome }}
          TF_VALIDATE_OUTCOME: ${{ steps.validate.outcome }}
          TF_PLAN_OUTCOME: ${{ steps.plan.outcome }}
          WORKING_DIRECTORY: ${{ inputs.working_directory }}
        run: |
          tfplan=$(tofu show tfplan -no-color)

          echo "#### OpenTofu Format and Style 🖌\`$TF_FMT_OUTCOME\`
          #### OpenTofu Initialization ⚙\`$TF_INIT_OUTCOME\`
          #### OpenTofu Validation 🤖\`$TF_VALIDATE_OUTCOME\`
          #### OpenTofu Plan 📖\`$TF_PLAN_OUTCOME\`

          <details><summary>Show Plan</summary>

          \`\`\`tofu
          $tfplan
          \`\`\`

          </details>

          *Pusher: @$GITHUB_ACTOR, Action: \`$GITHUB_EVENT_NAME\`, Working Directory: \`$WORKING_DIRECTORY\`, Workflow: \`$GITHUB_WORKFLOW\`*" >> "$GITHUB_STEP_SUMMARY"

      - name: Create tarball
        id: tar
        # Only run if OpenTofu Plan succeeded with non-empty diff (changes present).
        if: steps.plan.outputs.exitcode == 2
        run: |
          tarball="$RUNNER_TEMP/$ARTIFACT_NAME.tar.gpg"
          tar -cv . | gpg -c --batch --passphrase "$ENCRYPTION_PASSWORD" -o "$tarball"
          echo "tarball=$tarball" >> "$GITHUB_OUTPUT"

      - name: Upload artifact
        id: upload
        if: steps.tar.outcome == 'success'
        uses: actions/upload-artifact@50769540e7f4bd5e21e526ee35c689e35e0d6874
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ steps.tar.outputs.tarball }}
          if-no-files-found: error
          # Automatically delete artifact after the workflow run time limit (35 days) to save storage space.
          # If a workflow reaches this limit, it will be cancelled and the artifact will no longer be needed.
          # Ref: https://docs.github.com/en/actions/learn-github-actions/usage-limits-billing-and-administration#usage-limits
          retention-days: 35

  tofu-apply:
    name: OpenTofu Apply
    needs: tofu-plan
    if: github.actor != 'dependabot[bot]' && needs.tofu-plan.outputs.upload-outcome == 'success'
    runs-on: ${{ inputs.runs_on }}
    environment: ${{ inputs.environment }}
    permissions:
      contents: read  # Required to checkout the repository
      id-token: write # Required to login to Azure using OIDC
      actions: write  # Required to delete the artifact

    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332

      - name: Download artifact
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ${{ inputs.working_directory }}

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@12f4debbf681675350b6cd1f0ff8ecfbda62027b
        with:
          tofu_version: ${{ inputs.tofu_version }}

      - name: Extract tarball
        run: |
          tarball="$ARTIFACT_NAME.tar.gpg"
          gpg -d --batch --passphrase "$ENCRYPTION_PASSWORD" "$tarball" | tar -xv
          rm "$tarball"

      - name: OpenTofu Apply
        run: tofu apply -auto-approve -input=false tfplan

      # Once the OpenTofu plan file has been applied, the artifact is no longer needed.
      # Delete it to save storage space.
      # There is currently no official action to do this, so we use the GitHub CLI instead.
      - name: Delete artifact
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACT_ID: ${{ needs.tofu-plan.outputs.artifact-id }}
        run: |
          gh api --method DELETE "/repos/$GITHUB_REPOSITORY/actions/artifacts/$ARTIFACT_ID" 1>/dev/null
          echo "Deleted artifact $ARTIFACT_NAME ($ARTIFACT_ID)"
